// src/components/tables/UsuariosTable/usuariosMock.js

export const usuariosMock = [
  {
    id: 1,
    apellido: 'BALOT',
    nombre: 'Luciano Nicolás',
    logon: 'luchobalot',
    jerarquia: 'Marinero Primero',
    destino: 'Servicio de Análisis Operativo Armas y Guerra Electrónica (SIAG)',
    nivel: 'Superadministrador',
    matriculaRevista: '451341-5',
    confianza: true,
    superConfianza: true,
    justicia: true,
    fechaCreacion: '2024-10-12T14:23:00',
    fechaModificacion: '2024-10-12T14:35:00',
    tipoClasificacion: 'Reservado',
  },
  {
    id: 2,
    apellido: 'PÉREZ',
    nombre: 'Juan',
    logon: 'juancito_perez',
    jerarquia: 'Cabo Segundo',
    destino: 'Servicio de Análisis Operativo Armas y Guerra Electrónica (SIAG)',
    nivel: 'Administrador',
    matriculaRevista: '382917-4',
    confianza: true,
    superConfianza: false,
    justicia: true,
    fechaCreacion: '2024-11-01T09:10:00',
    tipoClasificacion: 'Confidencial',
  },
  {
    id: 3,
    apellido: 'GÓMEZ',
    nombre: 'María',
    logon: 'gomezmaria03',
    jerarquia: 'Teniente de Fragata',
    destino: 'Servicio de Análisis Operativo Armas y Guerra Electrónica (SIAG)',
    nivel: 'Operador',
    matriculaRevista: '429813-2',
    confianza: false,
    superConfianza: false,
    justicia: false,
    fechaCreacion: '2024-09-28T16:45:00',
    tipoClasificacion: 'Público',
  },
  {
    id: 4,
    apellido: 'RODRÍGUEZ',
    nombre: 'Carlos',
    logon: 'rodriguezcarlos',
    jerarquia: 'Suboficial Principal',
    destino: 'Servicio de Análisis Operativo Armas y Guerra Electrónica (SIAG)',
    nivel: 'Usuario',
    matriculaRevista: '391245-6',
    confianza: true,
    superConfianza: false,
    justicia: false,
    fechaCreacion: '2024-08-15T11:32:00',
    tipoClasificacion: 'Confidencial',
  },
  {
    id: 5,
    apellido: 'LÓPEZ',
    nombre: 'Ana',
    logon: 'analopez',
    jerarquia: 'Cabo Primero',
    destino: 'Hospital Naval Puerto Belgrano (HNPB)',
    nivel: 'Operador',
    matriculaRevista: '402315-9',
    confianza: false,
    superConfianza: false,
    fechaCreacion: '2024-10-05T18:20:00',
    justicia: false,
    tipoClasificacion: 'Reservado',
  },
  {
    "id": 6,
    "apellido": "FERNÁNDEZ",
    "nombre": "Sofía",
    "logon": "sofiafdez",
    "jerarquia": "Cabo Primero",
    "destino": "Servicio de Análisis Operativo Armas y Guerra Electrónica (SIAG)",
    "nivel": "Operador",
    "matriculaRevista": "417892-3",
    "confianza": true,
    "superConfianza": false,
    "justicia": false,
    "fechaCreacion": "2024-10-20T10:12:00",
    "fechaModificacion": "2024-10-20T10:45:00",
    "tipoClasificacion": "Reservado"
  },
  {
    "id": 7,
    "apellido": "RAMÍREZ",
    "nombre": "Diego",
    "logon": "dramirez",
    "jerarquia": "Teniente de Navío",
    "destino": "Servicio de Análisis Operativo Armas y Guerra Electrónica (SIAG)",
    "nivel": "Administrador",
    "matriculaRevista": "398721-7",
    "confianza": true,
    "superConfianza": true,
    "justicia": true,
    "fechaCreacion": "2024-11-03T08:30:00",
    "tipoClasificacion": "Confidencial"
  },
  {
    "id": 8,
    "apellido": "SOSA",
    "nombre": "Martín",
    "logon": "msosa",
    "jerarquia": "Marinero Primero",
    "destino": "Base Naval Puerto Belgrano (BNPB)",
    "nivel": "Usuario",
    "matriculaRevista": "421563-1",
    "confianza": false,
    "superConfianza": false,
    "justicia": false,
    "fechaCreacion": "2024-07-19T14:50:00",
    "fechaModificacion": "2024-07-19T15:00:00",
    "tipoClasificacion": "Público"
  },
  {
    "id": 9,
    "apellido": "MARTÍNEZ",
    "nombre": "Carolina",
    "logon": "caromtz",
    "jerarquia": "Suboficial Segundo",
    "destino": "Hospital Naval Puerto Belgrano (HNPB)",
    "nivel": "Operador",
    "matriculaRevista": "385214-8",
    "confianza": true,
    "superConfianza": false,
    "justicia": true,
    "fechaCreacion": "2024-09-10T09:05:00",
    "tipoClasificacion": "Reservado"
  },
  {
    "id": 10,
    "apellido": "AGUIRRE",
    "nombre": "Federico",
    "logon": "faguirre",
    "jerarquia": "Cabo Segundo",
    "destino": "Servicio de Análisis Operativo Armas y Guerra Electrónica (SIAG)",
    "nivel": "Operador",
    "matriculaRevista": "412876-0",
    "confianza": false,
    "superConfianza": false,
    "justicia": false,
    "fechaCreacion": "2024-08-28T13:40:00",
    "tipoClasificacion": "Confidencial"
  }
];
