// src/components/tables/UsuariosTable/usuariosMock.js

export const usuariosMock = [
  {
    id: 1,
    apellido: 'BALOT',
    nombre: 'LUCIANO NICOLÁS',
    logon: 'luchobalot',
    jerarquia: 'Marinero Primero',
    destino: 'Servicio de Análisis Operativo Armas y Guerra Electrónica (SIAG)',
    nivel: 'Superadministrador',
    matriculaRevista: '451341-5',
    confianza: true,
    superConfianza: true,
    fechaCreacion: '2024-10-12T14:23:00',
    tipoClasificacion: 'Reservado',
  },
  {
    id: 2,
    apellido: 'PÉREZ',
    nombre: 'JUAN',
    logon: 'juancito_perez',
    jerarquia: 'Cabo Segundo',
    destino: 'Servicio de Análisis Operativo Armas y Guerra Electrónica (SIAG)',
    nivel: 'Administrador',
    matriculaRevista: '382917-4',
    confianza: true,
    superConfianza: false,
    fechaCreacion: '2024-11-01T09:10:00',
    tipoClasificacion: 'Confidencial',
  },
  {
    id: 3,
    apellido: 'GÓMEZ',
    nombre: 'MARÍA',
    logon: 'gomezmaria03',
    jerarquia: 'Teniente de Fragata',
    destino: 'Servicio de Análisis Operativo Armas y Guerra Electrónica (SIAG)',
    nivel: 'Operador',
    matriculaRevista: '429813-2',
    confianza: false,
    superConfianza: false,
    justicia: false,
    fechaCreacion: '2024-09-28T16:45:00',
    tipoClasificacion: 'Público',
  },
  {
    id: 4,
    apellido: 'RODRÍGUEZ',
    nombre: 'CARLOS',
    logon: 'rodriguezcarlos',
    jerarquia: 'Suboficial Principal',
    destino: 'Servicio de Análisis Operativo Armas y Guerra Electrónica (SIAG)',
    nivel: 'Usuario',
    matriculaRevista: '391245-6',
    confianza: true,
    superConfianza: false,
    justicia: false,
    fechaCreacion: '2024-08-15T11:32:00',
    tipoClasificacion: 'Confidencial',
  },
  {
    id: 5,
    apellido: 'LÓPEZ',
    nombre: 'ANA',
    logon: 'analopez',
    jerarquia: 'Cabo Primero',
    destino: 'Hospital Naval Puerto Belgrano (HNPB)',
    nivel: 'Operador',
    matriculaRevista: '402315-9',
    confianza: false,
    superConfianza: false,
    fechaCreacion: '2024-10-05T18:20:00',
    justicia: false,
    tipoClasificacion: 'Reservado',
  },
];
